### ISSUE TITLE
Gybe usage

### ISSUE THREAD

**Issue by Jorb19** [petermorrowdev/gybe#10]
Hello Peter!

I'm a IT student in my third year of school. I'm doing an internship where I need to create a web-app, which takes values from users and puts and generate an Kubernetes depoloyment.yaml. I found your Gybe project and it seems perfect for my use case, but I can't really seem to understand how it works precisely and how I add more variables to the chart.py. Is there any tutorial available? Or maybe you would like to help me personally?

Thank you in advance!

**Comment by petermorrowdev** [comment]
Hey @Jorb19! This reply might be a little late, but here's an example with FastAPI:

Install dependencies.

```bash
pip install gybe fastapi 'uvicorn[standard]' httpie
```

Write a simple `server.py`.

```python
from fastapi import FastAPI
from pydantic import BaseModel
import gybe.favorites.kubernetes as k8s


app = FastAPI()


class CreateK8sDeployment(BaseModel):
    name: str 
    image: str


@app.post("/k8s-deployments/", response_model=k8s.Deployment, response_model_exclude_none=True)
def create_k8s_deployment(req: CreateK8sDeployment) -> k8s.Deployment:
    spec = k8s.DeploymentSpec(
        replias=1,
        selector=dict(matchLabels=dict(app=req.name)),
        template=dict(
            metadata=dict(name=req.name),
            spec=k8s.PodSpec(
                containers=[
                    k8s.Container(
                        name=req.name,
                        image=req.image,
                        command=["sleep", "infinity"]
                    )
                ]
            )
        )
    )
    return k8s.Deployment(
        apiVersion="apps/v1",
        kind="Deployment",
        metadata=dict(name=req.name),
        spec=spec,
    )
```

Run your server in debug mode.

```bash
uvicorn server:app --reload
```

Open another shell and run httpie to test.

```bash
http POST http://127.0.0.1:8000/k8s-deployments/ name=python-sleep image=python:3
```

You'll see the kubernetes deployment manifest output in JSON format.


```json
{
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "metadata": {
        "name": "python-sleep"
    },
    "spec": {
        "selector": {
            "matchLabels": {
                "app": "python-sleep"
            }
        },
        "template": {
            "metadata": {
                "name": "python-sleep"
            },
            "spec": {
                "containers": [
                    {
                        "command": [
                            "sleep",
                            "infinity"
                        ],
                        "image": "python:3",
                        "name": "python-sleep"
                    }
                ]
            }
        }
    }
}
```

Byt, you could call `.dict(...)` on that deployment object and pass it to `yaml.safe_dump` to serialize the model to YAML format then change the response model to include a `str` for the deployment YAML or a [FileRepsonse](https://fastapi.tiangolo.com/advanced/custom-response/#fileresponse) to literally return a YAML file.


Hope this helps! Apologies for the delayed response.
